name: elastic_dashboard
description: A simple and modern dashboard for FRC.
publish_to: 'none'
version: 2024.1.1-beta

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  animations: ^2.0.7
  collection: ^1.17.1
  contextmenu: ^3.0.0
  dot_cast: ^1.2.0
  dropdown_button2: ^2.3.9
  elegant_notification: ^1.11.0
  file_selector: ^1.0.1
  flutter:
    sdk: flutter
  flutter_box_transform: ^0.4.2
  flutter_colorpicker: ^1.0.3
  flutter_fancy_tree_view: ^1.1.1
  flutter_hooks: ^0.20.0
  github: ^9.17.0
  http: ^0.13.6
  messagepack: ^0.2.1
  msgpack_dart: ^1.0.1
  package_info_plus: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.0.15
  patterns_canvas: ^0.4.0
  provider: ^6.0.5
  searchable_listview: ^2.7.0
  shared_preferences: ^2.1.2
  syncfusion_flutter_charts: ^23.1.44
  syncfusion_flutter_gauges: ^23.1.44
  titlebar_buttons: ^1.0.0
  transitioned_indexed_stack: ^1.0.2
  url_launcher: ^6.1.14
  uuid: ^4.2.1
  vector_math: ^2.1.4
  version: ^3.0.2
  visibility_detector: ^0.4.0+2
  web_socket_channel: ^2.4.0
  window_manager: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  msix: ^3.16.1
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/fields/

msix_config:
  display_name: Elastic
  publisher_display_name: Gold872
  logo_path: windows/logo.png
  icons_background_color: transparent
  languages: en-us
