name: elastic_dashboard
description: A modern customizable dashboard for FRC teams.
publish_to: 'none'
version: 2023.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  animations: ^2.0.7
  contextmenu: ^3.0.0
  file_selector: ^0.9.3
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_box_transform: ^0.4.2
  flutter_colorpicker: ^1.0.3
  flutter_fancy_tree_view: ^1.1.1
  flutter_hooks: ^0.20.0
  flutter_mjpeg: ^2.0.4
  http: ^0.13.6
  messagepack: ^0.2.1
  msgpack_dart: ^1.0.1
  path: ^1.8.3
  path_provider: ^2.0.15
  patterns_canvas: ^0.4.0
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  syncfusion_flutter_gauges: ^22.2.7
  titlebar_buttons: ^1.0.0
  transitioned_indexed_stack: ^1.0.2
  vector_math: ^2.1.4
  visibility_detector: ^0.4.0+2
  web_socket_channel: ^2.4.0
  window_manager: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.16.1
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/fields/

msix_config:
  display_name: Elastic
  publisher_display_name: Gold872
  logo_path: windows/logo.png
  icons_background_color: transparent
  languages: en-us